### ISSUE TITLE
Deployment exception occurs after modifying the org.wso2.carbon.ml.core-1.0.2

### ISSUE THREAD

**Issue by nessyhamsa** [wso2/carbon-ml#137]
Downloaded the carbon.ml.core 1.0.2 source code from github and  modified the algorithm linear regression and replaced the org.wso2.carbon.ml.core-1.0.2.jar in to the build location \wso2ml-1.0.0\repository\components\plugins. 
But while running the wso2server.bat with the error message : 
Error occuring while deploying webapp "E:\wso2ml-1.0.0\repository\deployment\server\webapps\api.war"

**Comment by maheshakya** [comment]
I think you need to rename that to `org.wso2.carbon.ml.core_1.0.2.jar`.
Please use WSO2 dev mailing (`dev@wso2.org`) list to discuss issues afterwards.
